name: Build TrollSpeed (.tipa)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  THEOS: ''
  XCODE_VERSION: '15.1'

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Install Homebrew dependencies
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install dpkg ldid make libplist openssl@3 zip
          echo "/usr/local/opt/make/libexec/gnubin" >> $GITHUB_PATH

      - name: Checkout XXTouchNG/theos
        uses: actions/checkout@v4
        with:
          repository: XXTouchNG/theos
          ref: 78ee784d8d3238982c9abdc58cd39919263648b1
          path: theos
          submodules: recursive

      - name: Add THEOS environment variables
        run: |
          rm -rf $GITHUB_WORKSPACE/theos/sdks
          echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV

      - name: Restore additional SDKs
        id: cached-sdks-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.THEOS }}/sdks
          key: ${{ runner.os }}-sdks-${{ env.XCODE_VERSION }}

      - if: ${{ steps.cached-sdks-restore.outputs.cache-hit != 'true' }}
        name: Checkout theos/sdks
        uses: actions/checkout@v4
        with:
          repository: theos/sdks
          ref: master
          path: ${{ env.THEOS }}/sdks

      - if: ${{ steps.cached-sdks-restore.outputs.cache-hit != 'true' }}
        name: Save SDKs
        id: cached-sdks-save
        uses: actions/cache/save@v4
        with:
          path: ${{ env.THEOS }}/sdks
          key: ${{ steps.cached-sdks-restore.outputs.cache-primary-key }}

      # ✅ نزيل المسار الفرعي Te حتى ينسخ المشروع في الجذر مباشرة
      - name: Checkout your project
        uses: actions/checkout@v4
        with:
          path: .
          submodules: recursive

      - name: Setup build environment
        run: |
          echo "Available SDKs: $(find $THEOS/sdks -name "*.sdk" -maxdepth 1 -print)"
          echo "THEOS=$THEOS"
          echo "Building TrollSpeed project..."

      # ✅ التصحيح النهائي لمسار البناء
      - name: Build TrollSpeed (.tipa)
        run: |
          echo "Current workspace: $(pwd)"
          echo "Listing structure..."
          ls -R
          chmod +x build.sh
          ./build.sh 1.0

      # ✅ رفع ملف .tipa كـ Artifact
      - name: Upload artifact (.tipa)
        uses: actions/upload-artifact@v4
        with:
          name: TrollSpeed
          path: packages/*.tipa

      # ✅ رفع تلقائي إلى Releases (اختياري)
      - name: Upload release (optional)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v1.0
          name: TrollSpeed v1.0
          body: "Automated TrollSpeed build via GitHub Actions"
          files: |
            packages/*.tipa
