name: Build TrollSpeed (.tipa)

on:
  workflow_dispatch:   # تشغيل يدوي
  push:
    branches: [ main ] # أوتوماتيكي عند أي تعديل على main

jobs:
  build:
    runs-on: macos-13   # نحتاج macOS لأنه يحتوي Xcode

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install make dpkg ldid xcpretty zip

      - name: Build using build.sh
        run: |
          chmod +x build.sh
          ./build.sh 1.0

      - name: Upload .tipa file
        uses: actions/upload-artifact@v4
        with:
          name: TrollSpeed
          path: packages/*.tipa
